import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {/* <div>
          <Link href={"/"}>home </Link>
          <Link href={"/about"}>about </Link>
          <Link href={"/contact"}>contact </Link>
          <Link href={"/users"}>Users </Link>
          <Link href={"/jokes"}>Jokes </Link>
          <Link href={"/al-quran"}>Al-quran </Link>
          </div> */}
        {children}
        <Toaster/>
          </ThemeProvider>
      </body>
    </html>
  );
}
